version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - api1:api1
    ports:
      - 8080:80
  api1:
    build: ./services/api1/
    volumes:
      - ./services/api1:/code
    links:
      - redis
  # api2:
    # build: ./services/api2/
    # volumes:
      # - ./services/api2:/code
    # links:
      # - redis
  redis:
    image: "redis:alpine"
